default[:tomcat][:dir] = "/usr/local/tomcat"
default[:tomcat][:user] = "cat"
default[:tomcat][:group] = "cat"
default[:tomcat][:port] = "9000"
default[:tomcat][:java_home] = "/usr/local/java"
default[:tomcat][:java_opts] = "\"-Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC\""
default[:tomcat][:desc] = "Tomcat Servlet Engine 8"
default[:tomcat][:default] = "/etc/default/tomcat8"
default[:tomcat][:jvm_tmp] = "/tmp/tomcat8-tmp"
default[:tomcat][:pid] = "/var/run/tomcat8.pid"
default[:tomcat][:catalinaopts] = "-DJENKINS_HOME=/usr/local/tomcat/webapps/jenkins/ -Xmx512m"

